export const authTypes = {
  REGISTER_AUTH_START: "REGISTER_AUTH_START",
  REGISTER_AUTH_SUCCESS: "REGISTER_AUTH_SUCCESS",
  REGISTER_AUTH_FAILURE: "REGISTER_AUTH_FAILURE",

  LOGIN_AUTH_START: "LOGIN_AUTH_START",
  LOGIN_AUTH_SUCCESS: "LOGIN_AUTH_SUCCESS",
  LOGIN_AUTH_FAILURE: "LOGIN_AUTH_FAILURE",

  LOGOUT_AUTH_SUCCESS: "LOGOUT_AUTH_SUCCESS",
};

export const userTypes = {
  GET_USERS_START: "GET_USERS_START",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILURE: "GET_USERS_FAILURE",

  GET_USER_START: "GET_USER_START",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILURE: "GET_USER_FAILURE",

  UPDATE_USER_START: "UPDATE_USER_START",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
};

export const categoryTypes = {
  GET_CATEGORIES_START: "GET_CATEGORIES_START",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",

  CREATE_CATEGORY_START: "CREATE_CATEGORY_START",
  CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
  CREATE_CATEGORY_FAILURE: "CREATE_CATEGORY_FAILURE",

  UPDATE_CATEGORY_START: "UPDATE_CATEGORY_START",
  UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",

  DELETE_CATEGORY_START: "DELETE_CATEGORY_START",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_FAILURE: "DELETE_CATEGORY_FAILURE",
};

export const postTypes = {
  GET_POSTS_START: "GET_POSTS_START",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_FAILURE: "GET_POSTS_FAILURE",

  GET_POST_START: "GET_POST_START",
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_FAILURE: "GET_POST_FAILURE",

  CREATE_POST_START: "CREATE_POST_START",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",

  UPDATE_POST_START: "UPDATE_POST_START",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILURE: "UPDATE_POST_FAILURE",

  DELETE_POST_START: "DELETE_POST_START",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
};

export const optionTypes = {
  SIDEBAR_SHOW: "SIDEBAR_SHOW",
  GET_CONFIG_AXIOS: "GET_CONFIG_AXIOS",
  REMOVE_CONFIG_AXIOS: "REMOVE_CONFIG_AXIOS",
};

export const bacsiTypes = {
  GET_BACSIS_START: "GET_BACSIS_START",
  GET_BACSIS_SUCCESS: "GET_BACSIS_SUCCESS",
  GET_BACSIS_FAILURE: "GET_BACSIS_FAILURE",

  GET_BACSI_START: "GET_BACSI_START",
  GET_BACSI_SUCCESS: "GET_BACSI_SUCCESS",
  GET_BACSI_FAILURE: "GET_BACSI_FAILURE",

  CREATE_BACSI_START: "CREATE_BACSI_START",
  CREATE_BACSI_SUCCESS: "CREATE_BACSI_SUCCESS",
  CREATE_BACSI_FAILURE: "CREATE_BACSI_FAILURE",

  UPDATE_BACSI_START: "UPDATE_BACSI_START",
  UPDATE_BACSI_SUCCESS: "UPDATE_BACSI_SUCCESS",
  UPDATE_BACSI_FAILURE: "UPDATE_BACSI_FAILURE",

  DELETE_BACSI_START: "DELETE_BACSI_START",
  DELETE_BACSI_SUCCESS: "DELETE_BACSI_SUCCESS",
  DELETE_BACSI_FAILURE: "DELETE_BACSI_FAILURE",
};

export const khoaTypes = {
  GET_KHOAS_START: "GET_KHOAS_START",
  GET_KHOAS_SUCCESS: "GET_KHOAS_SUCCESS",
  GET_KHOAS_FAILURE: "GET_KHOAS_FAILURE",

  GET_KHOA_START: "GET_KHOA_START",
  GET_KHOA_SUCCESS: "GET_KHOA_SUCCESS",
  GET_KHOA_FAILURE: "GET_KHOA_FAILURE",

  CREATE_KHOA_START: "CREATE_KHOA_START",
  CREATE_KHOA_SUCCESS: "CREATE_KHOA_SUCCESS",
  CREATE_KHOA_FAILURE: "CREATE_KHOA_FAILURE",

  UPDATE_KHOA_START: "UPDATE_KHOA_START",
  UPDATE_KHOA_SUCCESS: "UPDATE_KHOA_SUCCESS",
  UPDATE_KHOA_FAILURE: "UPDATE_KHOA_FAILURE",

  DELETE_KHOA_START: "DELETE_KHOA_START",
  DELETE_KHOA_SUCCESS: "DELETE_KHOA_SUCCESS",
  DELETE_KHOA_FAILURE: "DELETE_KHOA_FAILURE",
};
